---
layout:   post
title:    异常
date:     2020-03-16
author:   YXC
catalog:  true
tags:
    - java
---
# 异常

异常(Exception)是程序运行期间产生的非正常问题，可以被程序员解决。

## 常见异常

### RuntimeException

产生频繁，处理麻烦，由系统自动处理。

可通过添加逻辑判断处理来避免异常

* 算数异常(ArithmeticException)：如1/0
* 空指针异常(NullPointerException):如引用参数为null，调用其方法
* 数组下界越界异常(ArrayIndexOutOfBoundsException):int a[3]; a[3] = 5;
* 类型转换异常(ClassCastException):Animal a = new Dog(); Cat b = (Cat) a;
* 数字格式化异常(NumberFormatException):str = "ab12",调用Integer.parseInt(str).

### CheckedException

已检查异常：不做出处理无法通过编译。

处理方法：try/catch捕获异常、throws声明抛出。

#### 捕获异常

try-catch-finally，try执行一段程序，如果出现异常catch捕获，最后finally提供统一的程序出口(无论有没有异常)。

* try遇到异常时，后面代码不执行。
* catch可以有多句，常用方法有：toString()(显示异常类名和原因)；getMessage()(只显示原因)；printStackTrace()(跟踪异常发生时堆栈的内容)，catch捕获异常，子类在前父类在后：如果父类异常在前，则报错时先发现父类，都会按父类异常操作
* finally若有则唯一且必然执行，可进行关闭文件流等操作。finally即使遇见return也会执行，除非在遇见finally之前执行了System.exit(0);

![å¾6-10 å¼å¸¸å¤ç.png](https://www.sxt.cn/360shop/Public/admin/UEditor/20170520/1495273755315926.png)

```java
public class Test {
	public static void main(String[] args){
		FileReader reader = null; //声明
		try {
			reader = new FileReader("d:/1.txt"); //此处可能有异常
			char c1 = (char)reader.read();
			char c2 = (char)reader.read();
			System.out.println(""+ c1+ c2);
		}catch(FileNotFoundException e) { 
			//ctrl+t可查看异常类型父子关系，FileNotFoundException是IOException的子类
			e.printStackTrace();
		}catch(IOException e) { //先子类异常后父类
			e.printStackTrace();
		}
		finally {
			try {
				reader.close(); //关闭文件流		
			}catch(IOException e) {
				e.printStackTrace();
			}
		}	
	}
}  
```



#### 声明异常

当不确定如何处理一个异常时，可以将它向上抛出(throws)。

当抛出多个异常时，用逗号隔开。

PS：子类继承父类有声明异常时，子类抛出的异常应不超出父类声明范围。

## 自定义异常

* 当遇到JDK提供的标准异常类无法解决时，可自己创建异常类。
* 异常类若继承Exception，则为受检查异常，编译必须处理；若继承RuntimeException则不用处理
* 自定义异常应有2个构造器：默认构造器、带有详细信息的构造器

自定义异常类：

```java
class AgeException extends Exception{
	public AgeException() {
		//默认构造器
	}
	public AgeException(String message) {
		super(message); //调用父类方法传出异常信息的构造器
	}
}
```



补充异常输出：

```java
class Person{
	private int age;
	public void setAge(int age) throws AgeException{
		if(age<0) {
			throw new AgeException("年龄不能为负数"); //当年龄为负时，抛出异常
		}
		this.age = age;
	}
}
```

1. 若异常类继承RuntimeException，则：

   ```java
   public class Test {
   	public static void main(String[] args){
   			Person man = new Person();
   			man.setAge(-5);
   	}
   }  
   ```

   

2. 若异常类继承Exception，则：

   ```java
   public class Test {
   	public static void main(String[] args){
   			Person man = new Person();
   			try {
   				man.setAge(-5); //需用trycatch处理			
   			}catch(AgeException e){
   				e.printStackTrace();
   				System.exit(-1);
   			}
   	}
   }  
   ```
